# Generated by Django 4.1.5 on 2023-02-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='equipo',
            field=models.ManyToManyField(related_name='juegos', to='esports.equipo'),
        ),
    ]
