# Generated by Django 4.1.5 on 2023-02-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='noticia',
        ),
        migrations.AddField(
            model_name='imagen',
            name='noticia',
            field=models.ManyToManyField(related_name='imagen', to='noticias.noticias_daw'),
        ),
    ]
